apiVersion: v1
kind: Pod
metadata:
  name: chaoskotlindemoinit
spec:
  containers:
    - name: chaoskotlin
      image: dxjoke/chaoskotlindemo:2.4.4
      command:
        - java
        - -cp
        - chaos-1.0.0.jar
        - -Dloader.path=/data/chaos/cmsb-with-deps.jar
        - org.springframework.boot.loader.PropertiesLauncher
        - --spring.profiles.active=chaos-monkey
      volumeMounts:
        - name: chaos-storage
          mountPath: /data/chaos
      ports:
        - containerPort: 8080
  initContainers:
    - name: cmsb
      image: dxjoke/chaoskotlindemo:extJarOnly
      command:
        - cp
        - cmsb-with-deps.jar
        - /data/chaos
      volumeMounts:
        - name: chaos-storage
          mountPath: /data/chaos

  volumes:
    - name: chaos-storage
      emptyDir: {}
