apiVersion: v1
kind: Pod
metadata:
  name: chaoskotlindemo
spec:
  containers:
    - name: chaoskotlin
      image: dxjoke/chaoskotlindemo:2.4.4
      command: ['cp', 'chaos-1.0.0.jar', '/data/chaos']
      volumeMounts:
        - name: chaos-storage
          mountPath: /data/chaos

    - name: cmsb
      image: dxjoke/chaoskotlindemo:extJarOnly
      command:
        - java
        - -cp
        - ./data/chaos/chaos-1.0.0.jar
        - -Dlogging.level.de.codecentric.spring.boot.chaos.monkey=DEBUG
        - -Dloader.path=cmsb-with-deps.jar
        - org.springframework.boot.loader.PropertiesLauncher
        - --spring.profiles.active=chaos-monkey
      volumeMounts:
        - name: chaos-storage
          mountPath: /data/chaos
      ports:
        - containerPort: 8080


  volumes:
    - name: chaos-storage
      emptyDir: {}
